api_branch : origin/master
api_parser : ~
api_cfgmod : clone
api_runner : ~
api_paths  : src
env_make : ~
env_prep : get-composer
env_post : ci-coveralls,ci-codacy
php_conf : timezone
php_exts : ~
app_prep : dep-composer
app_post : ~
app_path : bin/teavee-google-web-fonts
pkg_name : teavee-google-web-fonts-bundle
pkg_desc : "a small bundle for configuring Google Web Font inclusions using Symfony's YAML configuration or direct service class calls, as well as a Twig extension for outputting the required URL."
pkg_bndl : true
