---

parameters :

    # Generator

    s.teavee_google_web_fonts.generator.class      : Scribe\Teavee\GoogleWebFontsBundle\Components\GoogleWebFonts\GoogleWebFonts

    # Twig Extension

    s.teavee_google_web_fonts.twig_extension.class : Scribe\Teavee\GoogleWebFontsBundle\Templating\Extension\GoogleWebFontsExtension

services :

    # Generator

    s.teavee_google_web_fonts.generator :
        class     : %s.teavee_google_web_fonts.generator.class%
        arguments :
            - %s.teavee_google_web_fonts.global.fonts%
        calls:
            - [setLinkTemplate, [%s.teavee_google_web_fonts.global.link_template%]]

    # Twig Extension

    s.teavee_google_web_fonts.twig_extension :
        class     : %s.teavee_google_web_fonts.twig_extension.class%
        arguments :
            - '@s.teavee_google_web_fonts.generator'
        tags :
            - { name : twig.extension }

...
